---
- hosts: all

  pre_tasks:
    - name: Update APT cache
      apt: update_cache=yes

  roles:
    - { role: "azavea.docker" }

  tasks:
    - name: Bring up a test container
      command: docker run busybox sh
      become: yes
